import type { AdminBanner, Launch, SiteSettings, Vehicle, WhatsAppNumber } from "@/types";

const photo = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1800&q=88`;

export const demoVehicles: Vehicle[] = [
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88101",
    slug: "porsche-911-carrera-2026",
    title: "Porsche 911 Carrera",
    brand: "Porsche",
    model: "911",
    version: "Carrera PDK",
    manufactureYear: 2025,
    modelYear: 2026,
    price: 879900,
    mileage: 1200,
    fuel: "Gasolina",
    transmission: "Automático",
    color: "Cinza Ágata",
    doors: 2,
    engine: "3.0 biturbo",
    power: "385 cv",
    category: "Esportivo",
    purpose: "sale",
    status: "available",
    description: "Um ícone reinterpretado com precisão. Configuração de baixa quilometragem, acabamento impecável e histórico integralmente documentado.",
    location: "Fortaleza, CE",
    featured: true,
    isLaunch: true,
    showPrice: true,
    priceOnRequest: false,
    images: [
      { id: "p1", url: "/images/hero-velocity.png", alt: "Cupê esportivo premium em arquitetura contemporânea", isCover: true },
      { id: "p2", url: photo("photo-1503376780353-7e6692767b70"), alt: "Esportivo em estrada aberta" },
      { id: "p3", url: photo("photo-1504215680853-026ed2a45def"), alt: "Detalhe automotivo esportivo" },
    ],
    features: ["Bancos esportivos elétricos", "Câmera 360°", "Apple CarPlay", "Chave presencial", "Piloto automático adaptativo"],
    createdAt: "2026-08-18T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88102",
    slug: "toyota-corolla-xei-2026",
    title: "Toyota Corolla XEi",
    brand: "Toyota",
    model: "Corolla",
    version: "XEi 2.0 Flex",
    manufactureYear: 2025,
    modelYear: 2026,
    price: 169900,
    mileage: 8400,
    fuel: "Flex",
    transmission: "Automático CVT",
    color: "Branco Pérola",
    doors: 4,
    engine: "2.0 Dynamic Force",
    power: "175 cv",
    category: "Sedã",
    purpose: "sale",
    status: "available",
    description: "Sedã equilibrado para quem exige conforto, confiabilidade e tecnologia em todos os trajetos.",
    location: "Fortaleza, CE",
    featured: true,
    isLaunch: false,
    showPrice: true,
    priceOnRequest: false,
    images: [{ id: "c1", url: photo("photo-1492144534655-ae79c964c9d7"), alt: "Sedã branco em cenário urbano", isCover: true }],
    features: ["Toyota Safety Sense", "Ar digital", "Câmera de ré", "Android Auto", "Bancos em couro"],
    createdAt: "2026-08-16T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88103",
    slug: "toyota-hilux-srx-2026",
    title: "Toyota Hilux SRX",
    brand: "Toyota",
    model: "Hilux",
    version: "SRX 2.8 4x4",
    manufactureYear: 2025,
    modelYear: 2026,
    price: 349900,
    mileage: 2600,
    fuel: "Diesel",
    transmission: "Automático",
    color: "Preto Attitude",
    doors: 4,
    engine: "2.8 Turbo Diesel",
    power: "204 cv",
    category: "Picape",
    purpose: "both",
    status: "reserved",
    description: "Força para longas distâncias e acabamento que torna a rotina mais confortável.",
    location: "Fortaleza, CE",
    featured: true,
    isLaunch: true,
    showPrice: true,
    priceOnRequest: false,
    dailyPrice: 890,
    images: [{ id: "h1", url: photo("photo-1533473359331-0135ef1b58bf"), alt: "Picape premium em estrada", isCover: true }],
    features: ["Tração 4x4", "Controle de descida", "Câmera 360°", "Capota marítima", "Piloto adaptativo"],
    createdAt: "2026-08-14T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88104",
    slug: "jeep-compass-limited-2026",
    title: "Jeep Compass Limited",
    brand: "Jeep",
    model: "Compass",
    version: "Limited T270",
    manufactureYear: 2025,
    modelYear: 2026,
    price: 224900,
    dailyPrice: 490,
    mileage: 7300,
    fuel: "Flex",
    transmission: "Automático",
    color: "Cinza Sting",
    doors: 4,
    engine: "1.3 Turbo",
    power: "185 cv",
    category: "SUV",
    purpose: "both",
    status: "available",
    description: "SUV versátil com pacote completo de assistência e conectividade.",
    location: "Fortaleza, CE",
    featured: false,
    isLaunch: false,
    showPrice: true,
    priceOnRequest: false,
    images: [{ id: "j1", url: photo("photo-1519641471654-76ce0107ad1b"), alt: "SUV cinza em terreno aberto", isCover: true }],
    features: ["Teto panorâmico", "Partida remota", "Park Assist", "Carregador por indução"],
    createdAt: "2026-08-12T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88105",
    slug: "bmw-320i-m-sport-2025",
    title: "BMW 320i M Sport",
    brand: "BMW",
    model: "320i",
    version: "M Sport",
    manufactureYear: 2024,
    modelYear: 2025,
    price: 329900,
    mileage: 11900,
    fuel: "Gasolina",
    transmission: "Automático",
    color: "Azul Portimão",
    doors: 4,
    engine: "2.0 TwinPower Turbo",
    power: "184 cv",
    category: "Sedã",
    purpose: "sale",
    status: "available",
    description: "Proporção clássica, condução precisa e configuração M Sport de presença marcante.",
    location: "Fortaleza, CE",
    featured: true,
    isLaunch: false,
    showPrice: false,
    priceOnRequest: true,
    images: [{ id: "b1", url: photo("photo-1555215695-3004980ad54e"), alt: "Sedã esportivo azul", isCover: true }],
    features: ["Head-up display", "Bancos elétricos", "Iluminação ambiente", "Assistente de faixa"],
    createdAt: "2026-08-10T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88106",
    slug: "volkswagen-t-cross-highline-2025",
    title: "Volkswagen T-Cross",
    brand: "Volkswagen",
    model: "T-Cross",
    version: "Highline 250 TSI",
    manufactureYear: 2024,
    modelYear: 2025,
    price: 159900,
    dailyPrice: 360,
    mileage: 16400,
    fuel: "Flex",
    transmission: "Automático",
    color: "Prata Pyrit",
    doors: 4,
    engine: "1.4 TSI",
    power: "150 cv",
    category: "SUV",
    purpose: "rental",
    status: "available",
    description: "SUV compacto, confortável e pronto para viagens ou rotina executiva.",
    location: "Fortaleza, CE",
    featured: false,
    isLaunch: false,
    showPrice: true,
    priceOnRequest: false,
    images: [{ id: "t1", url: photo("photo-1549317661-bd32c8ce0db2"), alt: "SUV compacto prata", isCover: true }],
    features: ["Painel digital", "ACC", "Sensor dianteiro", "Chave presencial"],
    createdAt: "2026-08-08T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88107",
    slug: "honda-civic-advanced-hybrid-2025",
    title: "Honda Civic Advanced",
    brand: "Honda",
    model: "Civic",
    version: "Advanced Hybrid",
    manufactureYear: 2024,
    modelYear: 2025,
    price: 274900,
    mileage: 9800,
    fuel: "Híbrido",
    transmission: "Automático e-CVT",
    color: "Cinza Basalto",
    doors: 4,
    engine: "2.0 Hybrid",
    power: "184 cv",
    category: "Sedã",
    purpose: "sale",
    status: "available",
    description: "Tecnologia híbrida com resposta imediata e cabine de execução minimalista.",
    location: "Fortaleza, CE",
    featured: false,
    isLaunch: true,
    showPrice: true,
    priceOnRequest: false,
    images: [{ id: "cv1", url: photo("photo-1590362891991-f776e747a588"), alt: "Sedã moderno cinza", isCover: true }],
    features: ["Honda Sensing", "Bose Premium", "Teto solar", "Câmera multivisão"],
    createdAt: "2026-08-06T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88108",
    slug: "ford-ranger-limited-2025",
    title: "Ford Ranger Limited",
    brand: "Ford",
    model: "Ranger",
    version: "Limited 3.0 V6",
    manufactureYear: 2024,
    modelYear: 2025,
    price: 359900,
    mileage: 18900,
    fuel: "Diesel",
    transmission: "Automático",
    color: "Laranja Delhi",
    doors: 4,
    engine: "3.0 V6 Turbo Diesel",
    power: "250 cv",
    category: "Picape",
    purpose: "sale",
    status: "available",
    description: "Desempenho V6, tecnologia de condução e robustez para qualquer terreno.",
    location: "Fortaleza, CE",
    featured: false,
    isLaunch: false,
    showPrice: true,
    priceOnRequest: false,
    images: [{ id: "r1", url: photo("photo-1551830820-330a71b99659"), alt: "Picape em paisagem aberta", isCover: true }],
    features: ["Matriz LED", "Bloqueio diferencial", "Piloto adaptativo", "Câmera 360°"],
    createdAt: "2026-08-04T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88109",
    slug: "mercedes-c200-amg-line-2025",
    title: "Mercedes-Benz C 200",
    brand: "Mercedes-Benz",
    model: "C 200",
    version: "AMG Line",
    manufactureYear: 2024,
    modelYear: 2025,
    price: 389900,
    mileage: 6700,
    fuel: "Híbrido leve",
    transmission: "Automático",
    color: "Preto Obsidiana",
    doors: 4,
    engine: "1.5 Turbo EQ Boost",
    power: "204 cv",
    category: "Sedã",
    purpose: "sale",
    status: "sold",
    description: "Cabine digital, acabamento AMG Line e o refinamento esperado de um sedã executivo.",
    location: "Fortaleza, CE",
    featured: false,
    isLaunch: false,
    showPrice: true,
    priceOnRequest: false,
    images: [{ id: "m1", url: photo("photo-1563720223185-11003d516935"), alt: "Sedã executivo preto", isCover: true }],
    features: ["MBUX", "Burmester", "Teto solar", "Pacote AMG Line"],
    createdAt: "2026-08-02T12:00:00Z",
  },
  {
    id: "d1f601ba-f59c-45da-82cb-515855f88110",
    slug: "audi-q5-performance-2025",
    title: "Audi Q5 Performance",
    brand: "Audi",
    model: "Q5",
    version: "S line quattro",
    manufactureYear: 2024,
    modelYear: 2025,
    price: 419900,
    dailyPrice: 990,
    mileage: 10200,
    fuel: "Gasolina",
    transmission: "S tronic",
    color: "Verde Distrito",
    doors: 4,
    engine: "2.0 TFSI",
    power: "265 cv",
    category: "SUV",
    purpose: "both",
    status: "rented",
    description: "SUV de porte equilibrado, tração quattro e cabine silenciosa para grandes deslocamentos.",
    location: "Fortaleza, CE",
    featured: false,
    isLaunch: false,
    showPrice: false,
    priceOnRequest: true,
    images: [{ id: "a1", url: photo("photo-1606664515524-ed2f786a0bd6"), alt: "SUV premium verde", isCover: true }],
    features: ["Virtual Cockpit", "Bang & Olufsen", "Quattro", "Matrix LED"],
    createdAt: "2026-07-30T12:00:00Z",
  },
];

export const demoLaunches: Launch[] = [
  { id: "l1", slug: "a-nova-era-do-911", title: "A nova era do 911", subtitle: "Precisão que atravessa gerações", excerpt: "O desenho permanece inconfundível. A tecnologia muda tudo o que acontece por baixo dele.", image: "/images/hero-velocity.png", date: "2026-08-18", featured: true, vehicleSlug: "porsche-911-carrera-2026" },
  { id: "l2", slug: "hibridos-sem-abrir-mao-do-prazer", title: "Eficiência com resposta", subtitle: "A condução híbrida amadureceu", excerpt: "Uma seleção que combina silêncio urbano, autonomia e a resposta que ainda faz diferença.", image: photo("photo-1592838064575-70ed626d3a0e"), date: "2026-08-06", featured: true, vehicleSlug: "honda-civic-advanced-hybrid-2025" },
  { id: "l3", slug: "picapes-para-alem-do-trabalho", title: "Força com outro acabamento", subtitle: "Picapes que também são cabine executiva", excerpt: "Capacidade real para estrada e conforto suficiente para atravessar o país.", image: photo("photo-1551830820-330a71b99659"), date: "2026-07-28", featured: false, vehicleSlug: "ford-ranger-limited-2025" },
];

export const demoBanners: AdminBanner[] = [
  { id: "40000000-0000-4000-8000-000000000001", title: "Porsche 911 Carrera", subtitle: "Um ícone, precisamente agora.", desktop: "/images/hero-velocity.png", mobile: "/images/hero-velocity.png", cta: "Conhecer veículo", url: "/veiculos/porsche-911-carrera-2026", active: true, order: 1 },
  { id: "40000000-0000-4000-8000-000000000002", title: "Mobilidade sem intervalo", subtitle: "Locação para cada distância.", desktop: photo("photo-1504215680853-026ed2a45def"), mobile: photo("photo-1504215680853-026ed2a45def"), cta: "Ver locações", url: "/veiculos?finalidade=rental", active: true, order: 2 },
  { id: "40000000-0000-4000-8000-000000000003", title: "Curadoria executiva", subtitle: "Sedãs escolhidos por configuração.", desktop: photo("photo-1492144534655-ae79c964c9d7"), mobile: photo("photo-1492144534655-ae79c964c9d7"), cta: "Explorar", url: "/veiculos", active: false, order: 3 },
];

export const demoWhatsApps: WhatsAppNumber[] = [
  { id: "w1", name: "Vendas", responsible: "Rafael", number: "+55 85 99999-1001", sector: "sales", defaultMessage: "Olá! Quero falar com um especialista em vendas.", active: true, primary: true, priority: 1 },
  { id: "w2", name: "Locação", responsible: "Marina", number: "+55 85 99999-1002", sector: "rental", defaultMessage: "Olá! Quero conhecer as opções de locação.", active: true, primary: false, priority: 2 },
  { id: "w3", name: "Atendimento", responsible: "Equipe Wellington", number: "+55 85 99999-1003", sector: "support", defaultMessage: "Olá! Preciso de atendimento.", active: true, primary: false, priority: 3 },
];

export const demoSettings: SiteSettings = {
  companyName: "Wellington Veículos",
  tradeName: "Wellington Veículos e Locações",
  slogan: "Curadoria para quem escolhe a estrada.",
  address: "Av. Washington Soares, 3200",
  city: "Fortaleza",
  state: "CE",
  phone: "+55 85 3200-2026",
  email: "contato@wellingtonveiculos.com.br",
  hours: "Seg a sex, 8h às 18h · Sáb, 8h às 13h",
  about: "Selecionamos automóveis com procedência, configuração relevante e uma experiência de atendimento à altura de cada escolha.",
  logoUrl: "",
  alternateLogoUrl: "",
  faviconUrl: "",
  mapsUrl: "",
  heroUrl: "/images/hero-velocity.png",
  primaryColor: "#08090A",
  accentColor: "#DFFF3F",
  showSoldVehicles: false,
  social: { instagram: "https://instagram.com", facebook: "https://facebook.com", tiktok: "https://tiktok.com", youtube: "https://youtube.com" },
};

export const demoStats = {
  totalVehicles: demoVehicles.length,
  available: demoVehicles.filter((item) => item.status === "available").length,
  sold: demoVehicles.filter((item) => item.status === "sold").length,
  rented: demoVehicles.filter((item) => item.status === "rented").length,
  archived: demoVehicles.filter((item) => item.status === "archived").length,
  unreadMessages: 4,
  newLeads: 12,
  views: 1842,
};
