import type { Metadata } from "next";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getLaunches } from "@/lib/data";

type Props = { params: Promise<{ slug: string }> };
export async function generateStaticParams() { return (await getLaunches()).map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const item = (await getLaunches()).find((launch) => launch.slug === slug); return item ? { title: item.title, description: item.excerpt, openGraph: { images: [item.image] } } : { title: "Editorial não encontrado" }; }
export default async function LaunchPage({ params }: Props) { const { slug } = await params; const item = (await getLaunches()).find((launch) => launch.slug === slug); if (!item) notFound(); return <article className="pb-24 pt-28"><header className="page-shell pb-10"><Link href="/lancamentos" className="mb-10 inline-flex items-center gap-2 text-xs text-muted"><ArrowLeft size={14} /> Voltar aos lançamentos</Link><p className="eyebrow text-acid">Editorial · {item.date}</p><h1 className="editorial-title mt-5 max-w-[14ch] text-5xl md:text-8xl">{item.title}</h1><p className="mt-6 max-w-2xl text-xl leading-8 text-white/65">{item.subtitle}</p></header><div className="relative aspect-[16/8] w-full overflow-hidden"><Image src={item.image} alt={item.title} fill priority sizes="100vw" className="object-cover" /></div><div className="page-shell grid gap-12 py-14 lg:grid-cols-[220px_1fr_220px]"><aside className="font-mono text-[10px] uppercase leading-5 text-muted">Por Wellington Editorial<br />Leitura: 4 min</aside><div className="space-y-7 text-lg leading-9 text-white/76"><p className="text-2xl font-medium text-white">{item.excerpt}</p><p>Há automóveis que chegam ao mercado apenas com uma lista maior de equipamentos. Outros mudam a relação entre desenho, engenharia e condução. É nessa segunda categoria que concentramos nossa atenção.</p><p>Nossa leitura considera o que muda na prática: resposta, ergonomia, tecnologia útil, valor de permanência e a sensação ao volante. Sem transformar especificações de demonstração em informação oficial.</p><p>Para conhecer a configuração relacionada a este editorial, converse com nossa equipe e confirme disponibilidade, preços e detalhes atualizados.</p>{item.vehicleSlug && <Link href={`/veiculos/${item.vehicleSlug}`} className="inline-flex items-center gap-2 bg-acid px-5 py-3 text-sm font-semibold text-canvas">Conhecer veículo relacionado <ArrowUpRight size={16} /></Link>}</div></div></article>; }
