"use client";

import { ArrowLeft, ArrowRight, ImagePlus, Star, Trash2 } from "lucide-react";
import Image from "next/image";
import { useRef, useState } from "react";
import { toast } from "sonner";

export type UploadImage = { id: string; url: string; file?: File; isCover: boolean };
export function VehicleImageUploader({ images, onChange }: { images: UploadImage[]; onChange: (images: UploadImage[]) => void }) {
  const inputRef = useRef<HTMLInputElement>(null); const [dragging,setDragging] = useState(false);
  function add(files: FileList | File[]) { const valid = Array.from(files).filter((file) => { if (!["image/jpeg","image/png","image/webp"].includes(file.type)) { toast.error(`${file.name}: formato não permitido.`); return false; } if (file.size > 8 * 1024 * 1024) { toast.error(`${file.name}: limite de 8 MB.`); return false; } return true; }); onChange([...images,...valid.map((file,index) => ({ id:crypto.randomUUID(),url:URL.createObjectURL(file),file,isCover:images.length === 0 && index === 0 }))]); }
  function remove(index: number) { const next = images.filter((_,i) => i !== index); if (images[index]?.file) URL.revokeObjectURL(images[index].url); if (images[index]?.isCover && next[0]) next[0] = {...next[0],isCover:true}; onChange(next); }
  function move(index:number,direction:number) { const target=index+direction; if (target < 0 || target >= images.length) return; const next=[...images]; [next[index],next[target]]=[next[target],next[index]]; onChange(next); }
  function cover(index:number) { onChange(images.map((image,i) => ({...image,isCover:i===index}))); }
  return <div><div onDragOver={(e) => {e.preventDefault();setDragging(true);}} onDragLeave={() => setDragging(false)} onDrop={(e) => {e.preventDefault();setDragging(false);add(e.dataTransfer.files);}} className={`grid min-h-32 cursor-pointer place-items-center border border-dashed p-5 text-center ${dragging ? "border-acid bg-acid/5" : "border-line"}`} onClick={() => inputRef.current?.click()}><div><ImagePlus className="mx-auto text-muted" /><p className="mt-3 text-sm font-medium">Arraste fotos ou clique para selecionar</p><p className="mt-1 text-[10px] text-muted">JPG, PNG ou WebP · máximo 8 MB por arquivo</p></div><input ref={inputRef} type="file" multiple accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(e) => e.target.files && add(e.target.files)} /></div>{images.length > 0 && <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{images.map((image,index) => <div key={image.id} className="border border-line bg-canvas p-2"><div className="relative aspect-[4/3] overflow-hidden"><Image src={image.url} alt={`Foto ${index+1}`} fill unoptimized={Boolean(image.file)} sizes="220px" className="object-cover" />{image.isCover && <span className="absolute left-2 top-2 bg-acid px-2 py-1 font-mono text-[8px] uppercase text-canvas">Capa</span>}</div><div className="mt-2 flex items-center justify-between"><span className="font-mono text-[9px] text-muted">{String(index+1).padStart(2,"0")}</span><div className="flex gap-1"><button type="button" onClick={() => move(index,-1)} disabled={index===0} className="grid size-8 place-items-center border border-line disabled:opacity-30" title="Mover para esquerda"><ArrowLeft size={13} /></button><button type="button" onClick={() => move(index,1)} disabled={index===images.length-1} className="grid size-8 place-items-center border border-line disabled:opacity-30" title="Mover para direita"><ArrowRight size={13} /></button><button type="button" onClick={() => cover(index)} className="grid size-8 place-items-center border border-line" title="Definir capa"><Star size={13} className={image.isCover ? "fill-acid text-acid" : ""} /></button><button type="button" onClick={() => remove(index)} className="grid size-8 place-items-center border border-line text-signal" title="Excluir"><Trash2 size={13} /></button></div></div></div>)}</div>}</div>;
}
