"use client";

import * as Dialog from "@radix-ui/react-dialog";
import useEmblaCarousel from "embla-carousel-react";
import { ChevronLeft, ChevronRight, Expand, X } from "lucide-react";
import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import type { VehicleImage } from "@/types";

export function VehicleGallery({ images }: { images: VehicleImage[] }) {
  const [selected, setSelected] = useState(0);
  const [emblaRef, emblaApi] = useEmblaCarousel({ loop: true });
  const select = useCallback((index: number) => { setSelected(index); emblaApi?.scrollTo(index); }, [emblaApi]);
  useEffect(() => { if (!emblaApi) return; const onSelect = () => setSelected(emblaApi.selectedScrollSnap()); emblaApi.on("select", onSelect); return () => { emblaApi.off("select", onSelect); }; }, [emblaApi]);

  return <Dialog.Root><div className="grid gap-2 lg:grid-cols-[1fr_160px]"><div className="relative aspect-[16/10] overflow-hidden bg-surface" ref={emblaRef}><div className="flex h-full">{images.map((image) => <div key={image.id} className="relative min-w-0 flex-[0_0_100%]"><Image src={image.url} alt={image.alt} fill priority sizes="(max-width: 1024px) 100vw, 80vw" className="object-cover" /></div>)}</div><button onClick={() => emblaApi?.scrollPrev()} className="absolute bottom-4 left-4 grid size-11 place-items-center bg-canvas/90" aria-label="Foto anterior"><ChevronLeft /></button><button onClick={() => emblaApi?.scrollNext()} className="absolute bottom-4 left-16 grid size-11 place-items-center bg-canvas/90" aria-label="Próxima foto"><ChevronRight /></button><Dialog.Trigger asChild><button className="absolute bottom-4 right-4 flex h-11 items-center gap-2 bg-canvas/90 px-4 text-xs" aria-label="Abrir galeria em tela cheia"><Expand size={15} /> <span className="hidden sm:inline">Tela cheia</span></button></Dialog.Trigger><span className="absolute right-4 top-4 bg-canvas/80 px-2 py-1 font-mono text-[10px]">{String(selected + 1).padStart(2,"0")} / {String(images.length).padStart(2,"0")}</span></div><div className="hidden gap-2 lg:grid">{images.slice(0,4).map((image,index) => <button key={image.id} onClick={() => select(index)} className={`relative min-h-0 overflow-hidden border ${selected === index ? "border-acid" : "border-transparent"}`} aria-label={`Ver foto ${index + 1}`}><Image src={image.url} alt="" fill sizes="160px" className="object-cover" /></button>)}</div></div><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-[80] bg-black/96" /><Dialog.Content className="fixed inset-0 z-[90] grid place-items-center p-3 md:p-10"><Dialog.Title className="sr-only">Galeria de fotos</Dialog.Title><Dialog.Description className="sr-only">Visualização ampliada das fotografias do veículo</Dialog.Description><div className="relative h-full w-full"><Image src={images[selected].url} alt={images[selected].alt} fill sizes="100vw" className="object-contain" /></div><Dialog.Close className="absolute right-4 top-4 grid size-12 place-items-center bg-white text-black" aria-label="Fechar galeria"><X /></Dialog.Close><button onClick={() => select((selected - 1 + images.length) % images.length)} className="absolute left-4 top-1/2 grid size-12 -translate-y-1/2 place-items-center bg-white text-black" aria-label="Foto anterior"><ChevronLeft /></button><button onClick={() => select((selected + 1) % images.length)} className="absolute right-4 top-1/2 grid size-12 -translate-y-1/2 place-items-center bg-white text-black" aria-label="Próxima foto"><ChevronRight /></button></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
