import { ArrowDownRight, ArrowUpRight, CarFront, Eye, MessageSquare, UserRoundSearch } from "lucide-react";
import Link from "next/link";
import { AdminTopbar } from "@/components/admin/admin-sidebar";
import { DashboardChart } from "@/components/admin/dashboard-chart";
import { getAdminAnalyticsData, getDashboardData, getVehicles } from "@/lib/data";

const fallbackActivity = [["Marina iniciou uma conversa sobre o Compass","2 min"],["Porsche 911 foi visualizado","5 min"],["Carlos alterou o status do Corolla","18 min"],["Hilux foi marcada como reservada","1 h"],["Novo lead pelo formulário de contato","2 h"]];

export default async function AdminDashboard() {
  const [dashboard, vehicles, analytics] = await Promise.all([getDashboardData(), getVehicles("authenticated"), getAdminAnalyticsData()]);
  const recentActivity = dashboard.activity.length ? dashboard.activity.map((item) => [String(item.metadata.title ?? item.action), relativeTime(item.created_at)]) : fallbackActivity;
  const stats = [["Veículos disponíveis",dashboard.stats.available,CarFront,"Estoque atual",true],["Novos contatos",dashboard.stats.newLeads,UserRoundSearch,"Pipeline",true],["Mensagens não lidas",dashboard.stats.unreadMessages,MessageSquare,"Chat",false],["Visualizações",dashboard.stats.views,Eye,"Total registrado",true]] as const;
  return <><AdminTopbar /><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow mb-2">Dashboard</p><h1 className="text-2xl font-semibold">Bom dia, Wellington.</h1><p className="mt-1 text-xs text-muted">Visão atualizada da operação</p></div><Link href="/admin/veiculos/novo" className="flex h-10 items-center justify-center gap-2 bg-acid px-4 text-xs font-semibold text-canvas">Adicionar veículo <ArrowUpRight size={15} /></Link></div><div className="grid gap-px overflow-hidden border border-line bg-line sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,Icon,trend,positive]) => <div key={label} className="bg-surface p-5"><div className="flex items-start justify-between"><Icon size={18} className="text-muted" /><span className={`flex items-center text-[10px] ${positive ? "text-acid" : "text-muted"}`}>{trend}{positive ? <ArrowUpRight size={12} /> : <ArrowDownRight size={12} />}</span></div><strong className="mt-7 block text-3xl">{new Intl.NumberFormat("pt-BR").format(value)}</strong><p className="mt-1 text-xs text-muted">{label}</p></div>)}</div><div className="mt-7 grid gap-7 xl:grid-cols-[1.5fr_0.85fr]"><section className="border border-line bg-surface"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="text-sm font-semibold">Desempenho</h2><p className="mt-1 text-[10px] text-muted">Visualizações e leads · últimos 7 dias</p></div><span className="text-[10px] text-muted">Última semana</span></div><div className="p-4"><DashboardChart data={analytics.series} /></div></section><section className="border border-line bg-surface"><div className="border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Atividade recente</h2></div><div>{recentActivity.map(([text,time],index) => <div key={`${text}-${time}`} className="flex gap-3 border-b border-line px-5 py-4 last:border-0"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${index < 2 ? "bg-acid" : "bg-muted"}`} /><div className="min-w-0"><p className="text-xs leading-5">{text}</p><p className="mt-1 font-mono text-[9px] text-muted">{time}</p></div></div>)}</div></section></div><section className="mt-7 border border-line bg-surface"><div className="flex items-center justify-between border-b border-line px-5 py-4"><h2 className="text-sm font-semibold">Estoque recente</h2><Link href="/admin/veiculos" className="text-[10px] text-acid">Ver todos</Link></div><div className="divide-y divide-line">{vehicles.slice(0,4).map((vehicle) => <div key={vehicle.id} className="grid gap-2 px-5 py-4 text-xs sm:grid-cols-[1fr_120px_100px_100px] sm:items-center"><strong>{vehicle.title}<span className="block font-normal text-muted">{vehicle.version}</span></strong><span>{vehicle.modelYear}</span><span className="capitalize text-muted">{vehicle.status}</span><Link href={`/admin/veiculos/${vehicle.id}/editar`} className="text-acid sm:text-right">Editar</Link></div>)}</div></section></>;
}

function relativeTime(date: string) { const minutes = Math.max(1, Math.round((Date.now() - Date.parse(date)) / 60000)); if (minutes < 60) return `${minutes} min atrás`; const hours = Math.round(minutes / 60); return hours < 24 ? `${hours} h atrás` : `${Math.round(hours / 24)} d atrás`; }
