import { z } from "zod";

export const vehicleSchema = z.object({
  id: z.string().uuid().optional(),
  title: z.string().min(3),
  slug: z.string().min(3),
  brand: z.string(),
  model: z.string(),
  version: z.string(),
  manufactureYear: z.coerce.number(),
  modelYear: z.coerce.number(),
  price: z.number().nullable(),
  dailyPrice: z.number().nullable().optional(),
  weeklyPrice: z.number().nullable().optional(),
  monthlyPrice: z.number().nullable().optional(),
  mileage: z.number(),
  fuel: z.string(),
  transmission: z.string(),
  color: z.string(),
  doors: z.number(),
  engine: z.string().optional(),
  power: z.string().optional(),
  category: z.string(),
  purpose: z.enum(["sale", "rental", "both"]),
  status: z.enum([
    "available",
    "reserved",
    "sold",
    "rented",
    "unavailable",
    "archived",
  ]),
  description: z.string(),
  location: z.string(),
  featured: z.boolean(),
  isLaunch: z.boolean(),
  isPromotion: z.boolean().optional(),
  showPrice: z.boolean(),
  priceOnRequest: z.boolean(),
  features: z.array(z.string()),
  images: z.array(
    z.object({
      url: z.string(),
      is_cover: z.boolean(),
      position: z.number(),
    }),
  ),
});

export function toVehicleRow(input: z.infer<typeof vehicleSchema>) {
  return {
    id: input.id,
    title: input.title,
    slug: input.slug,
    brand: input.brand,
    model: input.model,
    version: input.version,
    manufacture_year: input.manufactureYear,
    model_year: input.modelYear,
    price: input.price,
    daily_price: input.dailyPrice,
    weekly_price: input.weeklyPrice,
    monthly_price: input.monthlyPrice,
    mileage: input.mileage,
    fuel: input.fuel,
    transmission: input.transmission,
    color: input.color,
    doors: input.doors,
    engine: input.engine,
    power: input.power,
    category: input.category,
    purpose: input.purpose,
    status: input.status,
    description: input.description,
    location: input.location,
    featured: input.featured,
    is_launch: input.isLaunch,
    is_promotion: input.isPromotion,
    show_price: input.showPrice,
    price_on_request: input.priceOnRequest,
  };
}
