"use client";

import { ArrowRight, Eye, EyeOff, LoaderCircle } from "lucide-react";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";

export function LoginForm(){const router=useRouter();const params=useSearchParams();const[visible,setVisible]=useState(false);const[loading,setLoading]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const data=new FormData(event.currentTarget);try{if(!process.env.NEXT_PUBLIC_SUPABASE_URL){toast.info("Modo demonstração ativo.");router.push("/admin");return;}const supabase=createBrowserSupabaseClient();const{error}=await supabase.auth.signInWithPassword({email:String(data.get("email")),password:String(data.get("password"))});if(error)throw error;const next=params.get("next");const destination=next?.startsWith("/")&&!next.startsWith("//")?next:"/admin";window.location.replace(destination);}catch(error){toast.error(error instanceof Error?error.message:"Não foi possível entrar.");}finally{setLoading(false);}}return <form onSubmit={submit} className="mt-9 space-y-5"><label className="block"><span className="eyebrow mb-2 block">E-mail</span><input name="email" type="email" autoComplete="email" required className="h-12 w-full border border-line bg-canvas px-3 text-sm" placeholder="voce@empresa.com"/></label><label className="block"><span className="eyebrow mb-2 block">Senha</span><span className="relative block"><input name="password" type={visible?"text":"password"} autoComplete="current-password" required className="h-12 w-full border border-line bg-canvas px-3 pr-12 text-sm"/><button type="button" onClick={()=>setVisible((v)=>!v)} className="absolute right-1 top-1 grid size-10 place-items-center text-muted" aria-label={visible?"Ocultar senha":"Mostrar senha"}>{visible?<EyeOff size={16}/>:<Eye size={16}/>}</button></span></label><button disabled={loading} className="flex h-12 w-full items-center justify-center gap-2 bg-acid text-sm font-semibold text-canvas disabled:opacity-50">{loading?<LoaderCircle size={17} className="animate-spin"/>:<>Entrar no painel <ArrowRight size={17}/></>}</button><p className="text-center text-[10px] leading-4 text-muted">O acesso é exclusivo para usuários autorizados pela empresa.</p></form>}
